# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.sdb
# Libre Office Version: 7.2
from ..lang.event_object import EventObject as EventObject_a3d70b03
import typing
from ooo_uno.oenv import UNO_ENVIRONMENT, UNO_RUNTIME
_DYNAMIC = False
if (not typing.TYPE_CHECKING) and UNO_RUNTIME and UNO_ENVIRONMENT:
    _DYNAMIC = True
    from ooo_uno.helper import uno_helper

if typing.TYPE_CHECKING or _DYNAMIC is False:


    class RowChangeEvent(EventObject_a3d70b03):
        """
        Struct Class

        indicates the type of change action on the data source.

        See Also:
            `API RowChangeEvent <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1sdb_1_1RowChangeEvent.html>`_


        Note:
            | At runtime RowChangeEvent will be an actual uno struct however can seamlessly be treated as a regualr class.
            | At design time a class is presumed. This allows for better typings.
            | RowChangeEvent is a callable and can be treatead as a class and create instances.
        """

        def __init__(self, Action: typing.Optional[int] = None, Rows: typing.Optional[int] = None):
            self._action = Action
            self._rows = Rows

        @property
        def Action(self) -> int:
            """
            indicates the type of change.
            """
            return self._action
        
        @Action.setter
        def Action(self, value: int) -> None:
            self._action = value

        @property
        def Rows(self) -> int:
            """
            indicates the number of rows affected by the change.
            """
            return self._rows
        
        @Rows.setter
        def Rows(self, value: int) -> None:
            self._rows = value

if not typing.TYPE_CHECKING and _DYNAMIC:
    def _dynamic_struct() -> None:
        # Dynamically create uno struct using uno
        global RowChangeEvent
        order = ('Action', 'Rows')

        def _struct_init(*args, **kwargs):
            struct = uno_helper.create_uno_struct('com.sun.star.sdb.RowChangeEvent')
            for i, arg in enumerate(args):
                if arg is None:
                    continue
                setattr(struct, order[i], arg)
            for k, v in kwargs.items():
                setattr(struct, k, v)
            return struct
        RowChangeEvent = _struct_init

    _dynamic_struct()

__all__ = ['RowChangeEvent']
