# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.table
# Libre Office Version: 7.2
from typing import TYPE_CHECKING
from ooo.oenv import UNO_ENVIRONMENT, UNO_RUNTIME, UNO_NONE
_DYNAMIC = False
if (not TYPE_CHECKING) and UNO_RUNTIME and UNO_ENVIRONMENT:
    _DYNAMIC = True

if not TYPE_CHECKING and _DYNAMIC:
    def _dynamic_struct():
        import uno
        from com.sun.star.table import BorderLine as UBorderLine
        # Dynamically create uno com.sun.star.table.BorderLine using uno
        global BorderLine

        def _set_attr(struct):
            struct.__dict__['__ooo_ns__'] = 'com.sun.star.table'
            struct.__dict__['__ooo_full_ns__'] = 'com.sun.star.table.BorderLine'
            struct.__dict__['__ooo_type_name__'] = 'struct'

        def _struct_init(Color = UNO_NONE, InnerLineWidth = UNO_NONE, OuterLineWidth = UNO_NONE, LineDistance = UNO_NONE):
            ns = 'com.sun.star.table.BorderLine'
            if isinstance(Color, UBorderLine):
                inst = uno.createUnoStruct(ns, Color)
                _set_attr(inst)
                return inst
            struct = uno.createUnoStruct(ns)

            if not Color is UNO_NONE:
                if getattr(struct, 'Color') != Color:
                    setattr(struct, 'Color', Color)
            if not InnerLineWidth is UNO_NONE:
                if getattr(struct, 'InnerLineWidth') != InnerLineWidth:
                    setattr(struct, 'InnerLineWidth', InnerLineWidth)
            if not OuterLineWidth is UNO_NONE:
                if getattr(struct, 'OuterLineWidth') != OuterLineWidth:
                    setattr(struct, 'OuterLineWidth', OuterLineWidth)
            if not LineDistance is UNO_NONE:
                if getattr(struct, 'LineDistance') != LineDistance:
                    setattr(struct, 'LineDistance', LineDistance)
            _set_attr(struct)
            return struct
        BorderLine = _struct_init

    _dynamic_struct()
else:
    from ...lo.table.border_line import BorderLine as BorderLine

__all__ = ['BorderLine']

