# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.frame.status
# Libre Office Version: 7.2
import typing
from ooo_uno.oenv import UNO_ENVIRONMENT, UNO_RUNTIME
_DYNAMIC = False
if (not typing.TYPE_CHECKING) and UNO_RUNTIME and UNO_ENVIRONMENT:
    _DYNAMIC = True
    from ooo_uno.helper import uno_helper

if typing.TYPE_CHECKING or _DYNAMIC is False:


    class Template(object):
        """
        Struct Class

        contains an association between a style name and a value.
        
        **since**
        
            OOo 2.0

        See Also:
            `API Template <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1frame_1_1status_1_1Template.html>`_


        Note:
            | At runtime Template will be an actual uno struct however can seamlessly be treated as a regualr class.
            | At design time a class is presumed. This allows for better typings.
            | Template is a callable and can be treatead as a class and create instances.
        """

        def __init__(self, StyleName: typing.Optional[str] = None, StyleNameIdentifier: typing.Optional[str] = None, Value: typing.Optional[int] = None):
            self._style_name = StyleName
            self._style_name_identifier = StyleNameIdentifier
            self._value = Value

        @property
        def StyleName(self) -> str:
            """
            specifies a style name.
            """
            return self._style_name
        
        @StyleName.setter
        def StyleName(self, value: str) -> None:
            self._style_name = value

        @property
        def StyleNameIdentifier(self) -> str:
            """
            specifies an identifier name in English (only for standard style).
            
            **since**
            
                LO 7.2
            """
            return self._style_name_identifier
        
        @StyleNameIdentifier.setter
        def StyleNameIdentifier(self, value: str) -> None:
            self._style_name_identifier = value

        @property
        def Value(self) -> int:
            """
            specifies a value that is bound to the style name.
            """
            return self._value
        
        @Value.setter
        def Value(self, value: int) -> None:
            self._value = value

if not typing.TYPE_CHECKING and _DYNAMIC:
    def _dynamic_struct() -> None:
        # Dynamically create uno struct using uno
        global Template
        order = ('StyleName', 'StyleNameIdentifier', 'Value')

        def _struct_init(*args, **kwargs):
            struct = uno_helper.create_uno_struct('com.sun.star.frame.status.Template')
            for i, arg in enumerate(args):
                if arg is None:
                    continue
                setattr(struct, order[i], arg)
            for k, v in kwargs.items():
                setattr(struct, k, v)
            return struct
        Template = _struct_init

    _dynamic_struct()

__all__ = ['Template']
