# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Service Class
# this is a auto generated file generated by Cheetah
# Libre Office Version: 7.3
# Namespace: com.sun.star.graphic
from .x_emf_parser import XEmfParser as XEmfParser_bb680bc3

class EmfTools(XEmfParser_bb680bc3):
    """
    Service Class

    Service that describes the necessary interfaces and properties to handle emf files.
    
    Parses a WMF/EMF/EMF+ file to a sequence of B2DPrimitives for internal usage
    
    **since**
    
        LibreOffice 6.0

    See Also:
        `API EmfTools <https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1graphic_1_1EmfTools.html>`_
    """
    __ooo_ns__: str = 'com.sun.star.graphic'
    __ooo_full_ns__: str = 'com.sun.star.graphic.EmfTools'
    __ooo_type_name__: str = 'service'



__all__ = ['EmfTools']

