# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from ...uno_obj.text.accessible_endnote_view import AccessibleEndnoteView as AccessibleEndnoteView
from ...uno_obj.text.accessible_footnote_view import AccessibleFootnoteView as AccessibleFootnoteView
from ...uno_obj.text.accessible_header_footer_view import AccessibleHeaderFooterView as AccessibleHeaderFooterView
from ...uno_obj.text.accessible_page_view import AccessiblePageView as AccessiblePageView
from ...uno_obj.text.accessible_paragraph_view import AccessibleParagraphView as AccessibleParagraphView
from ...uno_obj.text.accessible_text_document_page_view import AccessibleTextDocumentPageView as AccessibleTextDocumentPageView
from ...uno_obj.text.accessible_text_document_view import AccessibleTextDocumentView as AccessibleTextDocumentView
from ...uno_obj.text.accessible_text_embedded_object import AccessibleTextEmbeddedObject as AccessibleTextEmbeddedObject
from ...uno_obj.text.accessible_text_frame_view import AccessibleTextFrameView as AccessibleTextFrameView
from ...uno_obj.text.accessible_text_graphic_object import AccessibleTextGraphicObject as AccessibleTextGraphicObject
from ...uno_obj.text.author_display_format import AuthorDisplayFormat as AuthorDisplayFormat
from ...uno_obj.text.author_display_format import AuthorDisplayFormatEnum as AuthorDisplayFormatEnum
from ...uno_obj.text.auto_text_container import AutoTextContainer as AutoTextContainer
from ...uno_obj.text.auto_text_entry import AutoTextEntry as AutoTextEntry
from ...uno_obj.text.auto_text_group import AutoTextGroup as AutoTextGroup
from ...uno_obj.text.base_frame import BaseFrame as BaseFrame
from ...uno_obj.text.base_frame_properties import BaseFrameProperties as BaseFrameProperties
from ...uno_obj.text.base_index import BaseIndex as BaseIndex
from ...uno_obj.text.base_index_mark import BaseIndexMark as BaseIndexMark
from ...uno_obj.text.bibliography import Bibliography as Bibliography
from ...uno_obj.text.bibliography_data_field import BibliographyDataField as BibliographyDataField
from ...uno_obj.text.bibliography_data_field import BibliographyDataFieldEnum as BibliographyDataFieldEnum
from ...uno_obj.text.bibliography_data_type import BibliographyDataType as BibliographyDataType
from ...uno_obj.text.bibliography_data_type import BibliographyDataTypeEnum as BibliographyDataTypeEnum
from ...uno_obj.text.bookmark import Bookmark as Bookmark
from ...uno_obj.text.bookmarks import Bookmarks as Bookmarks
from ...uno_obj.text.cell import Cell as Cell
from ...uno_obj.text.cell_properties import CellProperties as CellProperties
from ...uno_obj.text.cell_range import CellRange as CellRange
from ...uno_obj.text.chained_text_frame import ChainedTextFrame as ChainedTextFrame
from ...uno_obj.text.chapter_format import ChapterFormat as ChapterFormat
from ...uno_obj.text.chapter_format import ChapterFormatEnum as ChapterFormatEnum
from ...uno_obj.text.chapter_numbering_rule import ChapterNumberingRule as ChapterNumberingRule
from ...uno_obj.text.character_compression_type import CharacterCompressionType as CharacterCompressionType
from ...uno_obj.text.character_compression_type import CharacterCompressionTypeEnum as CharacterCompressionTypeEnum
from ...uno_obj.text.column_separator_style import ColumnSeparatorStyle as ColumnSeparatorStyle
from ...uno_obj.text.column_separator_style import ColumnSeparatorStyleEnum as ColumnSeparatorStyleEnum
from ...uno_obj.text.content_index import ContentIndex as ContentIndex
from ...uno_obj.text.content_index_mark import ContentIndexMark as ContentIndexMark
from ...uno_obj.text.control_character import ControlCharacter as ControlCharacter
from ...uno_obj.text.control_character import ControlCharacterEnum as ControlCharacterEnum
from ...uno_obj.text.date_display_format import DateDisplayFormat as DateDisplayFormat
from ...uno_obj.text.date_display_format import DateDisplayFormatEnum as DateDisplayFormatEnum
from ...uno_obj.text.default_numbering_provider import DefaultNumberingProvider as DefaultNumberingProvider
from ...uno_obj.text.defaults import Defaults as Defaults
from ...uno_obj.text.dependent_text_field import DependentTextField as DependentTextField
from ...uno_obj.text.document_index import DocumentIndex as DocumentIndex
from ...uno_obj.text.document_index_level_format import DocumentIndexLevelFormat as DocumentIndexLevelFormat
from ...uno_obj.text.document_index_mark import DocumentIndexMark as DocumentIndexMark
from ...uno_obj.text.document_index_mark_asian import DocumentIndexMarkAsian as DocumentIndexMarkAsian
from ...uno_obj.text.document_index_paragraph_styles import DocumentIndexParagraphStyles as DocumentIndexParagraphStyles
from ...uno_obj.text.document_indexes import DocumentIndexes as DocumentIndexes
from ...uno_obj.text.document_settings import DocumentSettings as DocumentSettings
from ...uno_obj.text.document_statistic import DocumentStatistic as DocumentStatistic
from ...uno_obj.text.document_statistic import DocumentStatisticEnum as DocumentStatisticEnum
from ...uno_obj.text.endnote import Endnote as Endnote
from ...uno_obj.text.endnote_settings import EndnoteSettings as EndnoteSettings
from ...uno_obj.text.filename_display_format import FilenameDisplayFormat as FilenameDisplayFormat
from ...uno_obj.text.filename_display_format import FilenameDisplayFormatEnum as FilenameDisplayFormatEnum
from ...uno_obj.text.font_emphasis import FontEmphasis as FontEmphasis
from ...uno_obj.text.font_emphasis import FontEmphasisEnum as FontEmphasisEnum
from ...uno_obj.text.font_relief import FontRelief as FontRelief
from ...uno_obj.text.font_relief import FontReliefEnum as FontReliefEnum
from ...uno_obj.text.footnote import Footnote as Footnote
from ...uno_obj.text.footnote_numbering import FootnoteNumbering as FootnoteNumbering
from ...uno_obj.text.footnote_numbering import FootnoteNumberingEnum as FootnoteNumberingEnum
from ...uno_obj.text.footnote_settings import FootnoteSettings as FootnoteSettings
from ...uno_obj.text.footnotes import Footnotes as Footnotes
from ...uno_obj.text.generic_text_document import GenericTextDocument as GenericTextDocument
from ...uno_obj.text.global_document import GlobalDocument as GlobalDocument
from ...uno_obj.text.global_settings import GlobalSettings as GlobalSettings
from ...uno_obj.text.graphic_crop import GraphicCrop as GraphicCrop
from ...uno_obj.text.hori_orientation import HoriOrientation as HoriOrientation
from ...uno_obj.text.hori_orientation import HoriOrientationEnum as HoriOrientationEnum
from ...uno_obj.text.hori_orientation_format import HoriOrientationFormat as HoriOrientationFormat
from ...uno_obj.text.horizontal_adjust import HorizontalAdjust as HorizontalAdjust
from ...uno_obj.text.illustrations_index import IllustrationsIndex as IllustrationsIndex
from ...uno_obj.text.in_content_metadata import InContentMetadata as InContentMetadata
from ...uno_obj.text.invalid_text_content_exception import InvalidTextContentException as InvalidTextContentException
from ...uno_obj.text.label_follow import LabelFollow as LabelFollow
from ...uno_obj.text.label_follow import LabelFollowEnum as LabelFollowEnum
from ...uno_obj.text.line_numbering_properties import LineNumberingProperties as LineNumberingProperties
from ...uno_obj.text.mail_merge import MailMerge as MailMerge
from ...uno_obj.text.mail_merge_event import MailMergeEvent as MailMergeEvent
from ...uno_obj.text.mail_merge_type import MailMergeType as MailMergeType
from ...uno_obj.text.mail_merge_type import MailMergeTypeEnum as MailMergeTypeEnum
from ...uno_obj.text.module_dispatcher import ModuleDispatcher as ModuleDispatcher
from ...uno_obj.text.note_print_mode import NotePrintMode as NotePrintMode
from ...uno_obj.text.numbering_level import NumberingLevel as NumberingLevel
from ...uno_obj.text.numbering_rules import NumberingRules as NumberingRules
from ...uno_obj.text.numbering_style import NumberingStyle as NumberingStyle
from ...uno_obj.text.object_index import ObjectIndex as ObjectIndex
from ...uno_obj.text.page_footnote_info import PageFootnoteInfo as PageFootnoteInfo
from ...uno_obj.text.page_number_type import PageNumberType as PageNumberType
from ...uno_obj.text.page_print_settings import PagePrintSettings as PagePrintSettings
from ...uno_obj.text.paragraph import Paragraph as Paragraph
from ...uno_obj.text.paragraph_enumeration import ParagraphEnumeration as ParagraphEnumeration
from ...uno_obj.text.paragraph_vert_align import ParagraphVertAlign as ParagraphVertAlign
from ...uno_obj.text.paragraph_vert_align import ParagraphVertAlignEnum as ParagraphVertAlignEnum
from ...uno_obj.text.placeholder_type import PlaceholderType as PlaceholderType
from ...uno_obj.text.placeholder_type import PlaceholderTypeEnum as PlaceholderTypeEnum
from ...uno_obj.text.position_and_space_mode import PositionAndSpaceMode as PositionAndSpaceMode
from ...uno_obj.text.position_and_space_mode import PositionAndSpaceModeEnum as PositionAndSpaceModeEnum
from ...uno_obj.text.position_layout_dir import PositionLayoutDir as PositionLayoutDir
from ...uno_obj.text.position_layout_dir import PositionLayoutDirEnum as PositionLayoutDirEnum
from ...uno_obj.text.print_settings import PrintSettings as PrintSettings
from ...uno_obj.text.redline_portion import RedlinePortion as RedlinePortion
from ...uno_obj.text.reference_field_part import ReferenceFieldPart as ReferenceFieldPart
from ...uno_obj.text.reference_field_part import ReferenceFieldPartEnum as ReferenceFieldPartEnum
from ...uno_obj.text.reference_field_source import ReferenceFieldSource as ReferenceFieldSource
from ...uno_obj.text.reference_field_source import ReferenceFieldSourceEnum as ReferenceFieldSourceEnum
from ...uno_obj.text.reference_mark import ReferenceMark as ReferenceMark
from ...uno_obj.text.reference_marks import ReferenceMarks as ReferenceMarks
from ...uno_obj.text.rel_orientation import RelOrientation as RelOrientation
from ...uno_obj.text.rel_orientation import RelOrientationEnum as RelOrientationEnum
from ...uno_obj.text.ruby_adjust import RubyAdjust as RubyAdjust
from ...uno_obj.text.ruby_position import RubyPosition as RubyPosition
from ...uno_obj.text.ruby_position import RubyPositionEnum as RubyPositionEnum
from ...uno_obj.text.section_file_link import SectionFileLink as SectionFileLink
from ...uno_obj.text.set_variable_type import SetVariableType as SetVariableType
from ...uno_obj.text.set_variable_type import SetVariableTypeEnum as SetVariableTypeEnum
from ...uno_obj.text.shape import Shape as Shape
from ...uno_obj.text.size_type import SizeType as SizeType
from ...uno_obj.text.size_type import SizeTypeEnum as SizeTypeEnum
from ...uno_obj.text.table_column_separator import TableColumnSeparator as TableColumnSeparator
from ...uno_obj.text.table_columns import TableColumns as TableColumns
from ...uno_obj.text.table_index import TableIndex as TableIndex
from ...uno_obj.text.table_rows import TableRows as TableRows
from ...uno_obj.text.template_display_format import TemplateDisplayFormat as TemplateDisplayFormat
from ...uno_obj.text.template_display_format import TemplateDisplayFormatEnum as TemplateDisplayFormatEnum
from ...uno_obj.text.text import Text as Text
from ...uno_obj.text.text_column import TextColumn as TextColumn
from ...uno_obj.text.text_column_sequence import TextColumnSequence as TextColumnSequence
from ...uno_obj.text.text_columns import TextColumns as TextColumns
from ...uno_obj.text.text_content import TextContent as TextContent
from ...uno_obj.text.text_content_anchor_type import TextContentAnchorType as TextContentAnchorType
from ...uno_obj.text.text_content_collection import TextContentCollection as TextContentCollection
from ...uno_obj.text.text_cursor import TextCursor as TextCursor
from ...uno_obj.text.text_document import TextDocument as TextDocument
from ...uno_obj.text.text_document_view import TextDocumentView as TextDocumentView
from ...uno_obj.text.text_embedded_object import TextEmbeddedObject as TextEmbeddedObject
from ...uno_obj.text.text_embedded_objects import TextEmbeddedObjects as TextEmbeddedObjects
from ...uno_obj.text.text_field import TextField as TextField
from ...uno_obj.text.text_field_enumeration import TextFieldEnumeration as TextFieldEnumeration
from ...uno_obj.text.text_field_master import TextFieldMaster as TextFieldMaster
from ...uno_obj.text.text_field_masters import TextFieldMasters as TextFieldMasters
from ...uno_obj.text.text_fields import TextFields as TextFields
from ...uno_obj.text.text_frame import TextFrame as TextFrame
from ...uno_obj.text.text_frames import TextFrames as TextFrames
from ...uno_obj.text.text_graphic_object import TextGraphicObject as TextGraphicObject
from ...uno_obj.text.text_graphic_objects import TextGraphicObjects as TextGraphicObjects
from ...uno_obj.text.text_grid_mode import TextGridMode as TextGridMode
from ...uno_obj.text.text_grid_mode import TextGridModeEnum as TextGridModeEnum
from ...uno_obj.text.text_layout_cursor import TextLayoutCursor as TextLayoutCursor
from ...uno_obj.text.text_markup_descriptor import TextMarkupDescriptor as TextMarkupDescriptor
from ...uno_obj.text.text_markup_type import TextMarkupType as TextMarkupType
from ...uno_obj.text.text_markup_type import TextMarkupTypeEnum as TextMarkupTypeEnum
from ...uno_obj.text.text_page_style import TextPageStyle as TextPageStyle
from ...uno_obj.text.text_portion import TextPortion as TextPortion
from ...uno_obj.text.text_portion_enumeration import TextPortionEnumeration as TextPortionEnumeration
from ...uno_obj.text.text_position import TextPosition as TextPosition
from ...uno_obj.text.text_range import TextRange as TextRange
from ...uno_obj.text.text_range_content_properties import TextRangeContentProperties as TextRangeContentProperties
from ...uno_obj.text.text_range_selection import TextRangeSelection as TextRangeSelection
from ...uno_obj.text.text_ranges import TextRanges as TextRanges
from ...uno_obj.text.text_section import TextSection as TextSection
from ...uno_obj.text.text_sections import TextSections as TextSections
from ...uno_obj.text.text_sort_descriptor import TextSortDescriptor as TextSortDescriptor
from ...uno_obj.text.text_sort_descriptor2 import TextSortDescriptor2 as TextSortDescriptor2
from ...uno_obj.text.text_sortable import TextSortable as TextSortable
from ...uno_obj.text.text_table import TextTable as TextTable
from ...uno_obj.text.text_table_cursor import TextTableCursor as TextTableCursor
from ...uno_obj.text.text_table_row import TextTableRow as TextTableRow
from ...uno_obj.text.text_tables import TextTables as TextTables
from ...uno_obj.text.text_view_cursor import TextViewCursor as TextViewCursor
from ...uno_obj.text.time_display_format import TimeDisplayFormat as TimeDisplayFormat
from ...uno_obj.text.time_display_format import TimeDisplayFormatEnum as TimeDisplayFormatEnum
from ...uno_obj.text.user_data_part import UserDataPart as UserDataPart
from ...uno_obj.text.user_data_part import UserDataPartEnum as UserDataPartEnum
from ...uno_obj.text.user_defined_index import UserDefinedIndex as UserDefinedIndex
from ...uno_obj.text.user_field_format import UserFieldFormat as UserFieldFormat
from ...uno_obj.text.user_field_format import UserFieldFormatEnum as UserFieldFormatEnum
from ...uno_obj.text.user_index import UserIndex as UserIndex
from ...uno_obj.text.user_index_mark import UserIndexMark as UserIndexMark
from ...uno_obj.text.vert_orientation import VertOrientation as VertOrientation
from ...uno_obj.text.vert_orientation import VertOrientationEnum as VertOrientationEnum
from ...uno_obj.text.vert_orientation_format import VertOrientationFormat as VertOrientationFormat
from ...uno_obj.text.view_settings import ViewSettings as ViewSettings
from ...uno_obj.text.web_document import WebDocument as WebDocument
from ...uno_obj.text.wrap_influence_on_position import WrapInfluenceOnPosition as WrapInfluenceOnPosition
from ...uno_obj.text.wrap_influence_on_position import WrapInfluenceOnPositionEnum as WrapInfluenceOnPositionEnum
from ...uno_obj.text.wrap_text_mode import WrapTextMode as WrapTextMode
from ...uno_obj.text.writing_mode import WritingMode as WritingMode
from ...uno_obj.text.writing_mode2 import WritingMode2 as WritingMode2
from ...uno_obj.text.writing_mode2 import WritingMode2Enum as WritingMode2Enum
from ...uno_obj.text.x_auto_text_container import XAutoTextContainer as XAutoTextContainer
from ...uno_obj.text.x_auto_text_container2 import XAutoTextContainer2 as XAutoTextContainer2
from ...uno_obj.text.x_auto_text_entry import XAutoTextEntry as XAutoTextEntry
from ...uno_obj.text.x_auto_text_group import XAutoTextGroup as XAutoTextGroup
from ...uno_obj.text.x_bookmark_insert_tool import XBookmarkInsertTool as XBookmarkInsertTool
from ...uno_obj.text.x_bookmarks_supplier import XBookmarksSupplier as XBookmarksSupplier
from ...uno_obj.text.x_chapter_numbering_supplier import XChapterNumberingSupplier as XChapterNumberingSupplier
from ...uno_obj.text.x_default_numbering_provider import XDefaultNumberingProvider as XDefaultNumberingProvider
from ...uno_obj.text.x_dependent_text_field import XDependentTextField as XDependentTextField
from ...uno_obj.text.x_document_index import XDocumentIndex as XDocumentIndex
from ...uno_obj.text.x_document_index_mark import XDocumentIndexMark as XDocumentIndexMark
from ...uno_obj.text.x_document_indexes_supplier import XDocumentIndexesSupplier as XDocumentIndexesSupplier
from ...uno_obj.text.x_endnotes_settings_supplier import XEndnotesSettingsSupplier as XEndnotesSettingsSupplier
from ...uno_obj.text.x_endnotes_supplier import XEndnotesSupplier as XEndnotesSupplier
from ...uno_obj.text.x_flat_paragraph import XFlatParagraph as XFlatParagraph
from ...uno_obj.text.x_flat_paragraph_iterator import XFlatParagraphIterator as XFlatParagraphIterator
from ...uno_obj.text.x_flat_paragraph_iterator_provider import XFlatParagraphIteratorProvider as XFlatParagraphIteratorProvider
from ...uno_obj.text.x_footnote import XFootnote as XFootnote
from ...uno_obj.text.x_footnotes_settings_supplier import XFootnotesSettingsSupplier as XFootnotesSettingsSupplier
from ...uno_obj.text.x_footnotes_supplier import XFootnotesSupplier as XFootnotesSupplier
from ...uno_obj.text.x_form_field import XFormField as XFormField
from ...uno_obj.text.x_line_numbering_properties import XLineNumberingProperties as XLineNumberingProperties
from ...uno_obj.text.x_mail_merge_broadcaster import XMailMergeBroadcaster as XMailMergeBroadcaster
from ...uno_obj.text.x_mail_merge_listener import XMailMergeListener as XMailMergeListener
from ...uno_obj.text.x_marking_access import XMarkingAccess as XMarkingAccess
from ...uno_obj.text.x_multi_text_markup import XMultiTextMarkup as XMultiTextMarkup
from ...uno_obj.text.x_numbering_formatter import XNumberingFormatter as XNumberingFormatter
from ...uno_obj.text.x_numbering_rules_supplier import XNumberingRulesSupplier as XNumberingRulesSupplier
from ...uno_obj.text.x_numbering_type_info import XNumberingTypeInfo as XNumberingTypeInfo
from ...uno_obj.text.x_page_cursor import XPageCursor as XPageCursor
from ...uno_obj.text.x_page_printable import XPagePrintable as XPagePrintable
from ...uno_obj.text.x_paragraph_append import XParagraphAppend as XParagraphAppend
from ...uno_obj.text.x_paragraph_cursor import XParagraphCursor as XParagraphCursor
from ...uno_obj.text.x_paste_broadcaster import XPasteBroadcaster as XPasteBroadcaster
from ...uno_obj.text.x_paste_listener import XPasteListener as XPasteListener
from ...uno_obj.text.x_redline import XRedline as XRedline
from ...uno_obj.text.x_reference_marks_supplier import XReferenceMarksSupplier as XReferenceMarksSupplier
from ...uno_obj.text.x_relative_text_content_insert import XRelativeTextContentInsert as XRelativeTextContentInsert
from ...uno_obj.text.x_relative_text_content_remove import XRelativeTextContentRemove as XRelativeTextContentRemove
from ...uno_obj.text.x_ruby_selection import XRubySelection as XRubySelection
from ...uno_obj.text.x_sentence_cursor import XSentenceCursor as XSentenceCursor
from ...uno_obj.text.x_simple_text import XSimpleText as XSimpleText
from ...uno_obj.text.x_text import XText as XText
from ...uno_obj.text.x_text_append import XTextAppend as XTextAppend
from ...uno_obj.text.x_text_append_and_convert import XTextAppendAndConvert as XTextAppendAndConvert
from ...uno_obj.text.x_text_columns import XTextColumns as XTextColumns
from ...uno_obj.text.x_text_content import XTextContent as XTextContent
from ...uno_obj.text.x_text_content_append import XTextContentAppend as XTextContentAppend
from ...uno_obj.text.x_text_convert import XTextConvert as XTextConvert
from ...uno_obj.text.x_text_copy import XTextCopy as XTextCopy
from ...uno_obj.text.x_text_cursor import XTextCursor as XTextCursor
from ...uno_obj.text.x_text_document import XTextDocument as XTextDocument
from ...uno_obj.text.x_text_embedded_objects_supplier import XTextEmbeddedObjectsSupplier as XTextEmbeddedObjectsSupplier
from ...uno_obj.text.x_text_field import XTextField as XTextField
from ...uno_obj.text.x_text_fields_supplier import XTextFieldsSupplier as XTextFieldsSupplier
from ...uno_obj.text.x_text_frame import XTextFrame as XTextFrame
from ...uno_obj.text.x_text_frames_supplier import XTextFramesSupplier as XTextFramesSupplier
from ...uno_obj.text.x_text_graphic_objects_supplier import XTextGraphicObjectsSupplier as XTextGraphicObjectsSupplier
from ...uno_obj.text.x_text_markup import XTextMarkup as XTextMarkup
from ...uno_obj.text.x_text_portion_append import XTextPortionAppend as XTextPortionAppend
from ...uno_obj.text.x_text_range import XTextRange as XTextRange
from ...uno_obj.text.x_text_range_compare import XTextRangeCompare as XTextRangeCompare
from ...uno_obj.text.x_text_range_mover import XTextRangeMover as XTextRangeMover
from ...uno_obj.text.x_text_section import XTextSection as XTextSection
from ...uno_obj.text.x_text_sections_supplier import XTextSectionsSupplier as XTextSectionsSupplier
from ...uno_obj.text.x_text_shapes_supplier import XTextShapesSupplier as XTextShapesSupplier
from ...uno_obj.text.x_text_table import XTextTable as XTextTable
from ...uno_obj.text.x_text_table_cursor import XTextTableCursor as XTextTableCursor
from ...uno_obj.text.x_text_tables_supplier import XTextTablesSupplier as XTextTablesSupplier
from ...uno_obj.text.x_text_view_cursor import XTextViewCursor as XTextViewCursor
from ...uno_obj.text.x_text_view_cursor_supplier import XTextViewCursorSupplier as XTextViewCursorSupplier
from ...uno_obj.text.x_text_view_text_range_supplier import XTextViewTextRangeSupplier as XTextViewTextRangeSupplier
from ...uno_obj.text.x_word_cursor import XWordCursor as XWordCursor
