# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from ...uno_obj.drawing.accessible_draw_document_view import AccessibleDrawDocumentView as AccessibleDrawDocumentView
from ...uno_obj.drawing.accessible_graph_control import AccessibleGraphControl as AccessibleGraphControl
from ...uno_obj.drawing.accessible_graphic_shape import AccessibleGraphicShape as AccessibleGraphicShape
from ...uno_obj.drawing.accessible_image_bullet import AccessibleImageBullet as AccessibleImageBullet
from ...uno_obj.drawing.accessible_ole_shape import AccessibleOLEShape as AccessibleOLEShape
from ...uno_obj.drawing.accessible_shape import AccessibleShape as AccessibleShape
from ...uno_obj.drawing.accessible_slide_view import AccessibleSlideView as AccessibleSlideView
from ...uno_obj.drawing.accessible_slide_view_object import AccessibleSlideViewObject as AccessibleSlideViewObject
from ...uno_obj.drawing.alignment import Alignment as Alignment
from ...uno_obj.drawing.applet_shape import AppletShape as AppletShape
from ...uno_obj.drawing.arrangement import Arrangement as Arrangement
from ...uno_obj.drawing.background import Background as Background
from ...uno_obj.drawing.bezier_point import BezierPoint as BezierPoint
from ...uno_obj.drawing.bitmap_mode import BitmapMode as BitmapMode
from ...uno_obj.drawing.bitmap_table import BitmapTable as BitmapTable
from ...uno_obj.drawing.bound_volume import BoundVolume as BoundVolume
from ...uno_obj.drawing.camera_geometry import CameraGeometry as CameraGeometry
from ...uno_obj.drawing.canvas_feature import CanvasFeature as CanvasFeature
from ...uno_obj.drawing.canvas_feature import CanvasFeatureEnum as CanvasFeatureEnum
from ...uno_obj.drawing.caption_escape_direction import CaptionEscapeDirection as CaptionEscapeDirection
from ...uno_obj.drawing.caption_escape_direction import CaptionEscapeDirectionEnum as CaptionEscapeDirectionEnum
from ...uno_obj.drawing.caption_shape import CaptionShape as CaptionShape
from ...uno_obj.drawing.caption_type import CaptionType as CaptionType
from ...uno_obj.drawing.caption_type import CaptionTypeEnum as CaptionTypeEnum
from ...uno_obj.drawing.circle_kind import CircleKind as CircleKind
from ...uno_obj.drawing.closed_bezier_shape import ClosedBezierShape as ClosedBezierShape
from ...uno_obj.drawing.color_mode import ColorMode as ColorMode
from ...uno_obj.drawing.color_table import ColorTable as ColorTable
from ...uno_obj.drawing.connection_type import ConnectionType as ConnectionType
from ...uno_obj.drawing.connector_properties import ConnectorProperties as ConnectorProperties
from ...uno_obj.drawing.connector_shape import ConnectorShape as ConnectorShape
from ...uno_obj.drawing.connector_type import ConnectorType as ConnectorType
from ...uno_obj.drawing.control_shape import ControlShape as ControlShape
from ...uno_obj.drawing.coordinate_sequence import CoordinateSequence as CoordinateSequence
from ...uno_obj.drawing.coordinate_sequence_sequence import CoordinateSequenceSequence as CoordinateSequenceSequence
from ...uno_obj.drawing.custom_shape import CustomShape as CustomShape
from ...uno_obj.drawing.custom_shape_engine import CustomShapeEngine as CustomShapeEngine
from ...uno_obj.drawing.dash_style import DashStyle as DashStyle
from ...uno_obj.drawing.dash_table import DashTable as DashTable
from ...uno_obj.drawing.defaults import Defaults as Defaults
from ...uno_obj.drawing.direction3_d import Direction3D as Direction3D
from ...uno_obj.drawing.document_settings import DocumentSettings as DocumentSettings
from ...uno_obj.drawing.double_sequence import DoubleSequence as DoubleSequence
from ...uno_obj.drawing.double_sequence_sequence import DoubleSequenceSequence as DoubleSequenceSequence
from ...uno_obj.drawing.draw_page import DrawPage as DrawPage
from ...uno_obj.drawing.draw_pages import DrawPages as DrawPages
from ...uno_obj.drawing.draw_view_mode import DrawViewMode as DrawViewMode
from ...uno_obj.drawing.drawing_document import DrawingDocument as DrawingDocument
from ...uno_obj.drawing.drawing_document_draw_view import DrawingDocumentDrawView as DrawingDocumentDrawView
from ...uno_obj.drawing.drawing_document_factory import DrawingDocumentFactory as DrawingDocumentFactory
from ...uno_obj.drawing.ellipse_shape import EllipseShape as EllipseShape
from ...uno_obj.drawing.enhanced_custom_shape_adjustment_value import EnhancedCustomShapeAdjustmentValue as EnhancedCustomShapeAdjustmentValue
from ...uno_obj.drawing.enhanced_custom_shape_extrusion import EnhancedCustomShapeExtrusion as EnhancedCustomShapeExtrusion
from ...uno_obj.drawing.enhanced_custom_shape_geometry import EnhancedCustomShapeGeometry as EnhancedCustomShapeGeometry
from ...uno_obj.drawing.enhanced_custom_shape_glue_point_type import EnhancedCustomShapeGluePointType as EnhancedCustomShapeGluePointType
from ...uno_obj.drawing.enhanced_custom_shape_glue_point_type import EnhancedCustomShapeGluePointTypeEnum as EnhancedCustomShapeGluePointTypeEnum
from ...uno_obj.drawing.enhanced_custom_shape_handle import EnhancedCustomShapeHandle as EnhancedCustomShapeHandle
from ...uno_obj.drawing.enhanced_custom_shape_parameter import EnhancedCustomShapeParameter as EnhancedCustomShapeParameter
from ...uno_obj.drawing.enhanced_custom_shape_parameter_pair import EnhancedCustomShapeParameterPair as EnhancedCustomShapeParameterPair
from ...uno_obj.drawing.enhanced_custom_shape_parameter_type import EnhancedCustomShapeParameterType as EnhancedCustomShapeParameterType
from ...uno_obj.drawing.enhanced_custom_shape_parameter_type import EnhancedCustomShapeParameterTypeEnum as EnhancedCustomShapeParameterTypeEnum
from ...uno_obj.drawing.enhanced_custom_shape_path import EnhancedCustomShapePath as EnhancedCustomShapePath
from ...uno_obj.drawing.enhanced_custom_shape_segment import EnhancedCustomShapeSegment as EnhancedCustomShapeSegment
from ...uno_obj.drawing.enhanced_custom_shape_segment_command import EnhancedCustomShapeSegmentCommand as EnhancedCustomShapeSegmentCommand
from ...uno_obj.drawing.enhanced_custom_shape_segment_command import EnhancedCustomShapeSegmentCommandEnum as EnhancedCustomShapeSegmentCommandEnum
from ...uno_obj.drawing.enhanced_custom_shape_text_frame import EnhancedCustomShapeTextFrame as EnhancedCustomShapeTextFrame
from ...uno_obj.drawing.enhanced_custom_shape_text_path import EnhancedCustomShapeTextPath as EnhancedCustomShapeTextPath
from ...uno_obj.drawing.enhanced_custom_shape_text_path_mode import EnhancedCustomShapeTextPathMode as EnhancedCustomShapeTextPathMode
from ...uno_obj.drawing.escape_direction import EscapeDirection as EscapeDirection
from ...uno_obj.drawing.fill_properties import FillProperties as FillProperties
from ...uno_obj.drawing.fill_style import FillStyle as FillStyle
from ...uno_obj.drawing.flag_sequence import FlagSequence as FlagSequence
from ...uno_obj.drawing.flag_sequence_sequence import FlagSequenceSequence as FlagSequenceSequence
from ...uno_obj.drawing.generic_draw_page import GenericDrawPage as GenericDrawPage
from ...uno_obj.drawing.generic_drawing_document import GenericDrawingDocument as GenericDrawingDocument
from ...uno_obj.drawing.glue_point import GluePoint as GluePoint
from ...uno_obj.drawing.glue_point2 import GluePoint2 as GluePoint2
from ...uno_obj.drawing.gradient_table import GradientTable as GradientTable
from ...uno_obj.drawing.graphic_export_filter import GraphicExportFilter as GraphicExportFilter
from ...uno_obj.drawing.graphic_filter_request import GraphicFilterRequest as GraphicFilterRequest
from ...uno_obj.drawing.graphic_object_shape import GraphicObjectShape as GraphicObjectShape
from ...uno_obj.drawing.group_shape import GroupShape as GroupShape
from ...uno_obj.drawing.hatch import Hatch as Hatch
from ...uno_obj.drawing.hatch_style import HatchStyle as HatchStyle
from ...uno_obj.drawing.hatch_table import HatchTable as HatchTable
from ...uno_obj.drawing.homogen_matrix import HomogenMatrix as HomogenMatrix
from ...uno_obj.drawing.homogen_matrix3 import HomogenMatrix3 as HomogenMatrix3
from ...uno_obj.drawing.homogen_matrix4 import HomogenMatrix4 as HomogenMatrix4
from ...uno_obj.drawing.homogen_matrix_line import HomogenMatrixLine as HomogenMatrixLine
from ...uno_obj.drawing.homogen_matrix_line3 import HomogenMatrixLine3 as HomogenMatrixLine3
from ...uno_obj.drawing.homogen_matrix_line4 import HomogenMatrixLine4 as HomogenMatrixLine4
from ...uno_obj.drawing.horizontal_dimensioning import HorizontalDimensioning as HorizontalDimensioning
from ...uno_obj.drawing.layer import Layer as Layer
from ...uno_obj.drawing.layer_manager import LayerManager as LayerManager
from ...uno_obj.drawing.layer_type import LayerType as LayerType
from ...uno_obj.drawing.line_cap import LineCap as LineCap
from ...uno_obj.drawing.line_dash import LineDash as LineDash
from ...uno_obj.drawing.line_end_type import LineEndType as LineEndType
from ...uno_obj.drawing.line_joint import LineJoint as LineJoint
from ...uno_obj.drawing.line_properties import LineProperties as LineProperties
from ...uno_obj.drawing.line_shape import LineShape as LineShape
from ...uno_obj.drawing.line_style import LineStyle as LineStyle
from ...uno_obj.drawing.marker_table import MarkerTable as MarkerTable
from ...uno_obj.drawing.master_page import MasterPage as MasterPage
from ...uno_obj.drawing.master_pages import MasterPages as MasterPages
from ...uno_obj.drawing.measure_kind import MeasureKind as MeasureKind
from ...uno_obj.drawing.measure_properties import MeasureProperties as MeasureProperties
from ...uno_obj.drawing.measure_shape import MeasureShape as MeasureShape
from ...uno_obj.drawing.measure_text_horz_pos import MeasureTextHorzPos as MeasureTextHorzPos
from ...uno_obj.drawing.measure_text_vert_pos import MeasureTextVertPos as MeasureTextVertPos
from ...uno_obj.drawing.mirror_axis import MirrorAxis as MirrorAxis
from ...uno_obj.drawing.module_dispatcher import ModuleDispatcher as ModuleDispatcher
from ...uno_obj.drawing.normals_kind import NormalsKind as NormalsKind
from ...uno_obj.drawing.ole2_shape import OLE2Shape as OLE2Shape
from ...uno_obj.drawing.open_bezier_shape import OpenBezierShape as OpenBezierShape
from ...uno_obj.drawing.page_shape import PageShape as PageShape
from ...uno_obj.drawing.plugin_shape import PluginShape as PluginShape
from ...uno_obj.drawing.point_sequence import PointSequence as PointSequence
from ...uno_obj.drawing.point_sequence_sequence import PointSequenceSequence as PointSequenceSequence
from ...uno_obj.drawing.poly_line_shape import PolyLineShape as PolyLineShape
from ...uno_obj.drawing.poly_polygon_bezier_coords import PolyPolygonBezierCoords as PolyPolygonBezierCoords
from ...uno_obj.drawing.poly_polygon_bezier_descriptor import PolyPolygonBezierDescriptor as PolyPolygonBezierDescriptor
from ...uno_obj.drawing.poly_polygon_bezier_shape import PolyPolygonBezierShape as PolyPolygonBezierShape
from ...uno_obj.drawing.poly_polygon_descriptor import PolyPolygonDescriptor as PolyPolygonDescriptor
from ...uno_obj.drawing.poly_polygon_shape import PolyPolygonShape as PolyPolygonShape
from ...uno_obj.drawing.poly_polygon_shape3_d import PolyPolygonShape3D as PolyPolygonShape3D
from ...uno_obj.drawing.polygon_flags import PolygonFlags as PolygonFlags
from ...uno_obj.drawing.polygon_kind import PolygonKind as PolygonKind
from ...uno_obj.drawing.position3_d import Position3D as Position3D
from ...uno_obj.drawing.projection_mode import ProjectionMode as ProjectionMode
from ...uno_obj.drawing.qr_code import QRCode as QRCode
from ...uno_obj.drawing.qr_code_error_correction import QRCodeErrorCorrection as QRCodeErrorCorrection
from ...uno_obj.drawing.qr_code_error_correction import QRCodeErrorCorrectionEnum as QRCodeErrorCorrectionEnum
from ...uno_obj.drawing.rectangle_point import RectanglePoint as RectanglePoint
from ...uno_obj.drawing.rectangle_shape import RectangleShape as RectangleShape
from ...uno_obj.drawing.rotation_descriptor import RotationDescriptor as RotationDescriptor
from ...uno_obj.drawing.shade_mode import ShadeMode as ShadeMode
from ...uno_obj.drawing.shading_pattern import ShadingPattern as ShadingPattern
from ...uno_obj.drawing.shading_pattern import ShadingPatternEnum as ShadingPatternEnum
from ...uno_obj.drawing.shadow_properties import ShadowProperties as ShadowProperties
from ...uno_obj.drawing.shape import Shape as Shape
from ...uno_obj.drawing.shape_collection import ShapeCollection as ShapeCollection
from ...uno_obj.drawing.shapes import Shapes as Shapes
from ...uno_obj.drawing.slide_renderer import SlideRenderer as SlideRenderer
from ...uno_obj.drawing.slide_sorter import SlideSorter as SlideSorter
from ...uno_obj.drawing.snap_object_type import SnapObjectType as SnapObjectType
from ...uno_obj.drawing.text import Text as Text
from ...uno_obj.drawing.text_adjust import TextAdjust as TextAdjust
from ...uno_obj.drawing.text_animation_direction import TextAnimationDirection as TextAnimationDirection
from ...uno_obj.drawing.text_animation_kind import TextAnimationKind as TextAnimationKind
from ...uno_obj.drawing.text_fit_to_size_type import TextFitToSizeType as TextFitToSizeType
from ...uno_obj.drawing.text_horizontal_adjust import TextHorizontalAdjust as TextHorizontalAdjust
from ...uno_obj.drawing.text_properties import TextProperties as TextProperties
from ...uno_obj.drawing.text_shape import TextShape as TextShape
from ...uno_obj.drawing.text_vertical_adjust import TextVerticalAdjust as TextVerticalAdjust
from ...uno_obj.drawing.texture_kind import TextureKind as TextureKind
from ...uno_obj.drawing.texture_kind2 import TextureKind2 as TextureKind2
from ...uno_obj.drawing.texture_mode import TextureMode as TextureMode
from ...uno_obj.drawing.texture_projection_mode import TextureProjectionMode as TextureProjectionMode
from ...uno_obj.drawing.transparency_gradient_table import TransparencyGradientTable as TransparencyGradientTable
from ...uno_obj.drawing.vertical_dimensioning import VerticalDimensioning as VerticalDimensioning
from ...uno_obj.drawing.x_connectable_shape import XConnectableShape as XConnectableShape
from ...uno_obj.drawing.x_connector_shape import XConnectorShape as XConnectorShape
from ...uno_obj.drawing.x_control_shape import XControlShape as XControlShape
from ...uno_obj.drawing.x_custom_shape_engine import XCustomShapeEngine as XCustomShapeEngine
from ...uno_obj.drawing.x_custom_shape_handle import XCustomShapeHandle as XCustomShapeHandle
from ...uno_obj.drawing.x_draw_page import XDrawPage as XDrawPage
from ...uno_obj.drawing.x_draw_page_duplicator import XDrawPageDuplicator as XDrawPageDuplicator
from ...uno_obj.drawing.x_draw_page_expander import XDrawPageExpander as XDrawPageExpander
from ...uno_obj.drawing.x_draw_page_summarizer import XDrawPageSummarizer as XDrawPageSummarizer
from ...uno_obj.drawing.x_draw_page_supplier import XDrawPageSupplier as XDrawPageSupplier
from ...uno_obj.drawing.x_draw_pages import XDrawPages as XDrawPages
from ...uno_obj.drawing.x_draw_pages_supplier import XDrawPagesSupplier as XDrawPagesSupplier
from ...uno_obj.drawing.x_draw_sub_controller import XDrawSubController as XDrawSubController
from ...uno_obj.drawing.x_draw_view import XDrawView as XDrawView
from ...uno_obj.drawing.x_enhanced_custom_shape_defaulter import XEnhancedCustomShapeDefaulter as XEnhancedCustomShapeDefaulter
from ...uno_obj.drawing.x_glue_points_supplier import XGluePointsSupplier as XGluePointsSupplier
from ...uno_obj.drawing.x_graphic_export_filter import XGraphicExportFilter as XGraphicExportFilter
from ...uno_obj.drawing.x_layer import XLayer as XLayer
from ...uno_obj.drawing.x_layer_manager import XLayerManager as XLayerManager
from ...uno_obj.drawing.x_layer_supplier import XLayerSupplier as XLayerSupplier
from ...uno_obj.drawing.x_master_page_target import XMasterPageTarget as XMasterPageTarget
from ...uno_obj.drawing.x_master_pages_supplier import XMasterPagesSupplier as XMasterPagesSupplier
from ...uno_obj.drawing.x_presenter_helper import XPresenterHelper as XPresenterHelper
from ...uno_obj.drawing.x_selection_function import XSelectionFunction as XSelectionFunction
from ...uno_obj.drawing.x_shape import XShape as XShape
from ...uno_obj.drawing.x_shape_aligner import XShapeAligner as XShapeAligner
from ...uno_obj.drawing.x_shape_arranger import XShapeArranger as XShapeArranger
from ...uno_obj.drawing.x_shape_binder import XShapeBinder as XShapeBinder
from ...uno_obj.drawing.x_shape_combiner import XShapeCombiner as XShapeCombiner
from ...uno_obj.drawing.x_shape_descriptor import XShapeDescriptor as XShapeDescriptor
from ...uno_obj.drawing.x_shape_group import XShapeGroup as XShapeGroup
from ...uno_obj.drawing.x_shape_grouper import XShapeGrouper as XShapeGrouper
from ...uno_obj.drawing.x_shape_mirror import XShapeMirror as XShapeMirror
from ...uno_obj.drawing.x_shapes import XShapes as XShapes
from ...uno_obj.drawing.x_shapes2 import XShapes2 as XShapes2
from ...uno_obj.drawing.x_shapes3 import XShapes3 as XShapes3
from ...uno_obj.drawing.x_slide_preview_cache import XSlidePreviewCache as XSlidePreviewCache
from ...uno_obj.drawing.x_slide_preview_cache_listener import XSlidePreviewCacheListener as XSlidePreviewCacheListener
from ...uno_obj.drawing.x_slide_renderer import XSlideRenderer as XSlideRenderer
from ...uno_obj.drawing.x_slide_sorter_base import XSlideSorterBase as XSlideSorterBase
from ...uno_obj.drawing.x_universal_shape_descriptor import XUniversalShapeDescriptor as XUniversalShapeDescriptor
