# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from ...uno_obj.frame.app_dispatch_provider import AppDispatchProvider as AppDispatchProvider
from ...uno_obj.frame.auto_recovery import AutoRecovery as AutoRecovery
from ...uno_obj.frame.bibliography import Bibliography as Bibliography
from ...uno_obj.frame.border_widths import BorderWidths as BorderWidths
from ...uno_obj.frame.command_group import CommandGroup as CommandGroup
from ...uno_obj.frame.command_group import CommandGroupEnum as CommandGroupEnum
from ...uno_obj.frame.components import Components as Components
from ...uno_obj.frame.content_handler import ContentHandler as ContentHandler
from ...uno_obj.frame.content_handler_factory import ContentHandlerFactory as ContentHandlerFactory
from ...uno_obj.frame.control_command import ControlCommand as ControlCommand
from ...uno_obj.frame.control_event import ControlEvent as ControlEvent
from ...uno_obj.frame.controller import Controller as Controller
from ...uno_obj.frame.desktop import Desktop as Desktop
from ...uno_obj.frame.desktop_task import DesktopTask as DesktopTask
from ...uno_obj.frame.desktop_tasks import DesktopTasks as DesktopTasks
from ...uno_obj.frame.dispatch_descriptor import DispatchDescriptor as DispatchDescriptor
from ...uno_obj.frame.dispatch_helper import DispatchHelper as DispatchHelper
from ...uno_obj.frame.dispatch_information import DispatchInformation as DispatchInformation
from ...uno_obj.frame.dispatch_provider import DispatchProvider as DispatchProvider
from ...uno_obj.frame.dispatch_recorder import DispatchRecorder as DispatchRecorder
from ...uno_obj.frame.dispatch_recorder_supplier import DispatchRecorderSupplier as DispatchRecorderSupplier
from ...uno_obj.frame.dispatch_result_event import DispatchResultEvent as DispatchResultEvent
from ...uno_obj.frame.dispatch_result_state import DispatchResultState as DispatchResultState
from ...uno_obj.frame.dispatch_result_state import DispatchResultStateEnum as DispatchResultStateEnum
from ...uno_obj.frame.dispatch_statement import DispatchStatement as DispatchStatement
from ...uno_obj.frame.document_templates import DocumentTemplates as DocumentTemplates
from ...uno_obj.frame.double_initialization_exception import DoubleInitializationException as DoubleInitializationException
from ...uno_obj.frame.feature_state_event import FeatureStateEvent as FeatureStateEvent
from ...uno_obj.frame.frame import Frame as Frame
from ...uno_obj.frame.frame_action import FrameAction as FrameAction
from ...uno_obj.frame.frame_action_event import FrameActionEvent as FrameActionEvent
from ...uno_obj.frame.frame_control import FrameControl as FrameControl
from ...uno_obj.frame.frame_loader import FrameLoader as FrameLoader
from ...uno_obj.frame.frame_loader_factory import FrameLoaderFactory as FrameLoaderFactory
from ...uno_obj.frame.frame_search_flag import FrameSearchFlag as FrameSearchFlag
from ...uno_obj.frame.frame_search_flag import FrameSearchFlagEnum as FrameSearchFlagEnum
from ...uno_obj.frame.frames_container import FramesContainer as FramesContainer
from ...uno_obj.frame.global_event_broadcaster import GlobalEventBroadcaster as GlobalEventBroadcaster
from ...uno_obj.frame.illegal_argument_io_exception import IllegalArgumentIOException as IllegalArgumentIOException
from ...uno_obj.frame.infobar_type import InfobarType as InfobarType
from ...uno_obj.frame.infobar_type import InfobarTypeEnum as InfobarTypeEnum
from ...uno_obj.frame.layout_manager import LayoutManager as LayoutManager
from ...uno_obj.frame.layout_manager_events import LayoutManagerEvents as LayoutManagerEvents
from ...uno_obj.frame.layout_manager_events import LayoutManagerEventsEnum as LayoutManagerEventsEnum
from ...uno_obj.frame.media_type_detection_helper import MediaTypeDetectionHelper as MediaTypeDetectionHelper
from ...uno_obj.frame.module_manager import ModuleManager as ModuleManager
from ...uno_obj.frame.office_frame_loader import OfficeFrameLoader as OfficeFrameLoader
from ...uno_obj.frame.popup_menu_controller import PopupMenuController as PopupMenuController
from ...uno_obj.frame.popup_menu_controller_factory import PopupMenuControllerFactory as PopupMenuControllerFactory
from ...uno_obj.frame.protocol_handler import ProtocolHandler as ProtocolHandler
from ...uno_obj.frame.session_listener import SessionListener as SessionListener
from ...uno_obj.frame.session_manager import SessionManager as SessionManager
from ...uno_obj.frame.settings import Settings as Settings
from ...uno_obj.frame.start_module import StartModule as StartModule
from ...uno_obj.frame.statusbar_controller import StatusbarController as StatusbarController
from ...uno_obj.frame.statusbar_controller_factory import StatusbarControllerFactory as StatusbarControllerFactory
from ...uno_obj.frame.synchronous_frame_loader import SynchronousFrameLoader as SynchronousFrameLoader
from ...uno_obj.frame.task import Task as Task
from ...uno_obj.frame.task_creator import TaskCreator as TaskCreator
from ...uno_obj.frame.template_access import TemplateAccess as TemplateAccess
from ...uno_obj.frame.termination_veto_exception import TerminationVetoException as TerminationVetoException
from ...uno_obj.frame.title_changed_event import TitleChangedEvent as TitleChangedEvent
from ...uno_obj.frame.toolbar_controller import ToolbarController as ToolbarController
from ...uno_obj.frame.toolbar_controller_factory import ToolbarControllerFactory as ToolbarControllerFactory
from ...uno_obj.frame.transient_documents_document_content_factory import TransientDocumentsDocumentContentFactory as TransientDocumentsDocumentContentFactory
from ...uno_obj.frame.ui_command_description import UICommandDescription as UICommandDescription
from ...uno_obj.frame.unknown_module_exception import UnknownModuleException as UnknownModuleException
from ...uno_obj.frame.untitled_numbers_const import UntitledNumbersConst as UntitledNumbersConst
from ...uno_obj.frame.untitled_numbers_const import UntitledNumbersConstEnum as UntitledNumbersConstEnum
from ...uno_obj.frame.window_arrange import WindowArrange as WindowArrange
from ...uno_obj.frame.window_arrange import WindowArrangeEnum as WindowArrangeEnum
from ...uno_obj.frame.x_app_dispatch_provider import XAppDispatchProvider as XAppDispatchProvider
from ...uno_obj.frame.x_border_resize_listener import XBorderResizeListener as XBorderResizeListener
from ...uno_obj.frame.x_browse_history_registry import XBrowseHistoryRegistry as XBrowseHistoryRegistry
from ...uno_obj.frame.x_component_loader import XComponentLoader as XComponentLoader
from ...uno_obj.frame.x_component_registry import XComponentRegistry as XComponentRegistry
from ...uno_obj.frame.x_config_manager import XConfigManager as XConfigManager
from ...uno_obj.frame.x_control_notification_listener import XControlNotificationListener as XControlNotificationListener
from ...uno_obj.frame.x_controller import XController as XController
from ...uno_obj.frame.x_controller2 import XController2 as XController2
from ...uno_obj.frame.x_controller_border import XControllerBorder as XControllerBorder
from ...uno_obj.frame.x_desktop import XDesktop as XDesktop
from ...uno_obj.frame.x_desktop2 import XDesktop2 as XDesktop2
from ...uno_obj.frame.x_desktop_task import XDesktopTask as XDesktopTask
from ...uno_obj.frame.x_dispatch import XDispatch as XDispatch
from ...uno_obj.frame.x_dispatch_helper import XDispatchHelper as XDispatchHelper
from ...uno_obj.frame.x_dispatch_information_provider import XDispatchInformationProvider as XDispatchInformationProvider
from ...uno_obj.frame.x_dispatch_provider import XDispatchProvider as XDispatchProvider
from ...uno_obj.frame.x_dispatch_provider_interception import XDispatchProviderInterception as XDispatchProviderInterception
from ...uno_obj.frame.x_dispatch_provider_interceptor import XDispatchProviderInterceptor as XDispatchProviderInterceptor
from ...uno_obj.frame.x_dispatch_recorder import XDispatchRecorder as XDispatchRecorder
from ...uno_obj.frame.x_dispatch_recorder_supplier import XDispatchRecorderSupplier as XDispatchRecorderSupplier
from ...uno_obj.frame.x_dispatch_result_listener import XDispatchResultListener as XDispatchResultListener
from ...uno_obj.frame.x_document_templates import XDocumentTemplates as XDocumentTemplates
from ...uno_obj.frame.x_extended_filter_detection import XExtendedFilterDetection as XExtendedFilterDetection
from ...uno_obj.frame.x_filter_detect import XFilterDetect as XFilterDetect
from ...uno_obj.frame.x_frame import XFrame as XFrame
from ...uno_obj.frame.x_frame2 import XFrame2 as XFrame2
from ...uno_obj.frame.x_frame_action_listener import XFrameActionListener as XFrameActionListener
from ...uno_obj.frame.x_frame_loader import XFrameLoader as XFrameLoader
from ...uno_obj.frame.x_frame_loader_query import XFrameLoaderQuery as XFrameLoaderQuery
from ...uno_obj.frame.x_frame_set_model import XFrameSetModel as XFrameSetModel
from ...uno_obj.frame.x_frames import XFrames as XFrames
from ...uno_obj.frame.x_frames_supplier import XFramesSupplier as XFramesSupplier
from ...uno_obj.frame.x_global_event_broadcaster import XGlobalEventBroadcaster as XGlobalEventBroadcaster
from ...uno_obj.frame.x_infobar_provider import XInfobarProvider as XInfobarProvider
from ...uno_obj.frame.x_interceptor_info import XInterceptorInfo as XInterceptorInfo
from ...uno_obj.frame.x_layout_manager import XLayoutManager as XLayoutManager
from ...uno_obj.frame.x_layout_manager2 import XLayoutManager2 as XLayoutManager2
from ...uno_obj.frame.x_layout_manager_event_broadcaster import XLayoutManagerEventBroadcaster as XLayoutManagerEventBroadcaster
from ...uno_obj.frame.x_layout_manager_listener import XLayoutManagerListener as XLayoutManagerListener
from ...uno_obj.frame.x_load_event_listener import XLoadEventListener as XLoadEventListener
from ...uno_obj.frame.x_loadable import XLoadable as XLoadable
from ...uno_obj.frame.x_loader_factory import XLoaderFactory as XLoaderFactory
from ...uno_obj.frame.x_menu_bar_acceptor import XMenuBarAcceptor as XMenuBarAcceptor
from ...uno_obj.frame.x_menu_bar_merging_acceptor import XMenuBarMergingAcceptor as XMenuBarMergingAcceptor
from ...uno_obj.frame.x_model import XModel as XModel
from ...uno_obj.frame.x_model2 import XModel2 as XModel2
from ...uno_obj.frame.x_model3 import XModel3 as XModel3
from ...uno_obj.frame.x_module import XModule as XModule
from ...uno_obj.frame.x_module_manager import XModuleManager as XModuleManager
from ...uno_obj.frame.x_module_manager2 import XModuleManager2 as XModuleManager2
from ...uno_obj.frame.x_notifying_dispatch import XNotifyingDispatch as XNotifyingDispatch
from ...uno_obj.frame.x_popup_menu_controller import XPopupMenuController as XPopupMenuController
from ...uno_obj.frame.x_recordable_dispatch import XRecordableDispatch as XRecordableDispatch
from ...uno_obj.frame.x_session_manager_client import XSessionManagerClient as XSessionManagerClient
from ...uno_obj.frame.x_session_manager_listener import XSessionManagerListener as XSessionManagerListener
from ...uno_obj.frame.x_session_manager_listener2 import XSessionManagerListener2 as XSessionManagerListener2
from ...uno_obj.frame.x_status_listener import XStatusListener as XStatusListener
from ...uno_obj.frame.x_statusbar_controller import XStatusbarController as XStatusbarController
from ...uno_obj.frame.x_storable import XStorable as XStorable
from ...uno_obj.frame.x_storable2 import XStorable2 as XStorable2
from ...uno_obj.frame.x_sub_toolbar_controller import XSubToolbarController as XSubToolbarController
from ...uno_obj.frame.x_synchronous_dispatch import XSynchronousDispatch as XSynchronousDispatch
from ...uno_obj.frame.x_synchronous_frame_loader import XSynchronousFrameLoader as XSynchronousFrameLoader
from ...uno_obj.frame.x_task import XTask as XTask
from ...uno_obj.frame.x_tasks_supplier import XTasksSupplier as XTasksSupplier
from ...uno_obj.frame.x_terminate_listener import XTerminateListener as XTerminateListener
from ...uno_obj.frame.x_terminate_listener2 import XTerminateListener2 as XTerminateListener2
from ...uno_obj.frame.x_title import XTitle as XTitle
from ...uno_obj.frame.x_title_change_broadcaster import XTitleChangeBroadcaster as XTitleChangeBroadcaster
from ...uno_obj.frame.x_title_change_listener import XTitleChangeListener as XTitleChangeListener
from ...uno_obj.frame.x_toolbar_controller import XToolbarController as XToolbarController
from ...uno_obj.frame.x_toolbar_controller_listener import XToolbarControllerListener as XToolbarControllerListener
from ...uno_obj.frame.x_transient_documents_document_content_factory import XTransientDocumentsDocumentContentFactory as XTransientDocumentsDocumentContentFactory
from ...uno_obj.frame.x_transient_documents_document_content_identifier_factory import XTransientDocumentsDocumentContentIdentifierFactory as XTransientDocumentsDocumentContentIdentifierFactory
from ...uno_obj.frame.xui_controller_factory import XUIControllerFactory as XUIControllerFactory
from ...uno_obj.frame.xui_controller_registration import XUIControllerRegistration as XUIControllerRegistration
from ...uno_obj.frame.x_untitled_numbers import XUntitledNumbers as XUntitledNumbers
from ...uno_obj.frame.x_url_list import XUrlList as XUrlList
from ...uno_obj.frame.x_window_arranger import XWindowArranger as XWindowArranger
from ...uno_obj.frame.the_auto_recovery import theAutoRecovery as theAutoRecovery
from ...uno_obj.frame.the_desktop import theDesktop as theDesktop
from ...uno_obj.frame.the_global_event_broadcaster import theGlobalEventBroadcaster as theGlobalEventBroadcaster
from ...uno_obj.frame.the_popup_menu_controller_factory import thePopupMenuControllerFactory as thePopupMenuControllerFactory
from ...uno_obj.frame.the_statusbar_controller_factory import theStatusbarControllerFactory as theStatusbarControllerFactory
from ...uno_obj.frame.the_toolbar_controller_factory import theToolbarControllerFactory as theToolbarControllerFactory
from ...uno_obj.frame.the_ui_command_description import theUICommandDescription as theUICommandDescription
