# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.drawing
# Libre Office Version: 7.2
import typing
if typing.TYPE_CHECKING:
    from .position3_d import Position3D as Position3D_bddc0bc0


class BoundVolume(object):
    """
    Struct Class

    specifies a three-dimensional boundary volume with two positions.

    See Also:
        `API BoundVolume <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1drawing_1_1BoundVolume.html>`_
    """
    __ooo_ns__: str = 'com.sun.star.drawing'
    __ooo_full_ns__: str = 'com.sun.star.drawing.BoundVolume'
    __ooo_type_name__: str = 'struct'
    typeName: str = 'com.sun.star.drawing.BoundVolume'
    """Literal Constant ``com.sun.star.drawing.BoundVolume``"""


    def __init__(self, *args, **kwargs):
        """
        Constructor

        Other Arguments:
            First positinal arg can be another ``BoundVolume`` instance,
                if it is the only argument passed to contructor;
                Otherwise, postitional arguments are treated as ``BoundVolume``
                values. Following the order of ``Keyword Arguments``.

        Keyword Arguments:
            min (Position3D, optional): min value
            max (Position3D, optional): max value
        """
        self._min = None
        self._max = None

        key_order = ('min', 'max')
        arg_len = len(args)
        if arg_len == 1:
            if isinstance(args[0], BoundVolume):
                oth = args[0]
                for key in key_order:
                    setattr(self, key, getattr(oth, key))
                return

        if  arg_len > len(key_order):
            raise ValueError("BoundVolume.__init__() To many parameters")
        for i, arg in enumerate(args):
            setattr(self, key_order[i], arg)
        for k, v in kwargs.items():
            if k in key_order:
                setattr(self, k, v)

    @property
    def min(self) -> 'Position3D_bddc0bc0':
        """
        this is the minimum position inside the boundary volume.
        """
        return self._min
    
    @min.setter
    def min(self, value: 'Position3D_bddc0bc0') -> None:
        self._min = value

    @property
    def max(self) -> 'Position3D_bddc0bc0':
        """
        this is the maximum position inside the boundary volume.
        """
        return self._max
    
    @max.setter
    def max(self, value: 'Position3D_bddc0bc0') -> None:
        self._max = value


__all__ = ['BoundVolume']
