# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.awt
# Libre Office Version: 7.2
from ..lang.event_object import EventObject as EventObject_a3d70b03
import typing
if typing.TYPE_CHECKING:
    from .point import Point as Point_5fb2085e
    from .rectangle import Rectangle as Rectangle_84b109e9


class DockingEvent(EventObject_a3d70b03):
    """
    Struct Class

    specifies a docking event.

    See Also:
        `API DockingEvent <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1awt_1_1DockingEvent.html>`_
    """
    __ooo_ns__: str = 'com.sun.star.awt'
    __ooo_full_ns__: str = 'com.sun.star.awt.DockingEvent'
    __ooo_type_name__: str = 'struct'
    typeName: str = 'com.sun.star.awt.DockingEvent'
    """Literal Constant ``com.sun.star.awt.DockingEvent``"""

    def __init__(self, *args, **kwargs):
        """
        Constructor

        Other Arguments:
            First positinal arg can be another ``DockingEvent`` instance,
                if it is the only argument passed to contructor;
                Otherwise, postitional arguments are treated as ``DockingEvent``
                values. Following the order of ``Keyword Arguments``.

        Keyword Arguments:
            TrackingRectangle (Rectangle, optional): TrackingRectangle value
            MousePos (Point, optional): MousePos value
            bLiveMode (bool, optional): bLiveMode value
            bInteractive (bool, optional): bInteractive value
        """
        self._tracking_rectangle = None
        self._mouse_pos = None
        self._b_live_mode = None
        self._b_interactive = None

        key_order = ('TrackingRectangle', 'MousePos', 'bLiveMode', 'bInteractive')
        arg_len = len(args)
        if arg_len == 1:
            if isinstance(args[0], DockingEvent):
                oth = args[0]
                for key in key_order:
                    setattr(self, key, getattr(oth, key))
                return

        if  arg_len > len(key_order):
            raise ValueError("DockingEvent.__init__() To many parameters")
        for i, arg in enumerate(args):
            setattr(self, key_order[i], arg)
        for k, v in kwargs.items():
            if k in key_order:
                setattr(self, k, v)


    @property
    def TrackingRectangle(self) -> 'Rectangle_84b109e9':
        """
        specifies the current tracking rectangle
        """
        return self._tracking_rectangle
    
    @TrackingRectangle.setter
    def TrackingRectangle(self, value: 'Rectangle_84b109e9') -> None:
        self._tracking_rectangle = value

    @property
    def MousePos(self) -> 'Point_5fb2085e':
        """
        specifies the current mouse position in frame coordinates
        """
        return self._mouse_pos
    
    @MousePos.setter
    def MousePos(self, value: 'Point_5fb2085e') -> None:
        self._mouse_pos = value

    @property
    def bLiveMode(self) -> bool:
        """
        specifies if the layout should be adjusted immediately
        """
        return self._b_live_mode
    
    @bLiveMode.setter
    def bLiveMode(self, value: bool) -> None:
        self._b_live_mode = value

    @property
    def bInteractive(self) -> bool:
        """
        specifies if the docking procedure is interactive which means that the user is currently dragging the window to a new position if this member is FALSE the window will be docked or undocked immediately using the returned tracking rectangle
        """
        return self._b_interactive
    
    @bInteractive.setter
    def bInteractive(self, value: bool) -> None:
        self._b_interactive = value


__all__ = ['DockingEvent']
