# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Service Class
# this is a auto generated file generated by Cheetah
# Libre Office Version: 7.2
# Namespace: com.sun.star.table
from .cell_properties import CellProperties as CellProperties_d4360cbd
from .x_cell import XCell as XCell_70d408e8
from ..text.x_text import XText as XText_690408ca

class Cell(CellProperties_d4360cbd, XCell_70d408e8, XText_690408ca):
    """
    Service Class

    represents a single cell within a table.

    See Also:
        `API Cell <https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1table_1_1Cell.html>`_
    """
    __ooo_ns__: str = 'com.sun.star.table'
    __ooo_full_ns__: str = 'com.sun.star.table.Cell'
    __ooo_type_name__: str = 'service'



__all__ = ['Cell']

