# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.table
# Libre Office Version: 7.2
import typing
if typing.TYPE_CHECKING:
    from .border_line import BorderLine as BorderLine_a3f80af6


class TableBorder(object):
    """
    Struct Class

    contains the style settings of the border lines of all cells in a cell range.
    
    In a queried structure, the flags in TableBorder.Is...LineValid indicate that not all lines of the boxes have the same values.
    
    In a structure which is used for setting, these flags determine if the corresponding line should be set or if the old value should be kept.

    See Also:
        `API TableBorder <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1table_1_1TableBorder.html>`_
    """
    __ooo_ns__: str = 'com.sun.star.table'
    __ooo_full_ns__: str = 'com.sun.star.table.TableBorder'
    __ooo_type_name__: str = 'struct'
    typeName: str = 'com.sun.star.table.TableBorder'
    """Literal Constant ``com.sun.star.table.TableBorder``"""

    def __init__(self, *args, **kwargs):
        """
        Constructor

        Other Arguments:
            First positinal arg can be another ``TableBorder`` instance,
                if it is the only argument passed to contructor;
                Otherwise, postitional arguments are treated as ``TableBorder``
                values. Following the order of ``Keyword Arguments``.

        Keyword Arguments:
            TopLine (BorderLine, optional): TopLine value
            IsTopLineValid (bool, optional): IsTopLineValid value
            BottomLine (BorderLine, optional): BottomLine value
            IsBottomLineValid (bool, optional): IsBottomLineValid value
            LeftLine (BorderLine, optional): LeftLine value
            IsLeftLineValid (bool, optional): IsLeftLineValid value
            RightLine (BorderLine, optional): RightLine value
            IsRightLineValid (bool, optional): IsRightLineValid value
            HorizontalLine (BorderLine, optional): HorizontalLine value
            IsHorizontalLineValid (bool, optional): IsHorizontalLineValid value
            VerticalLine (BorderLine, optional): VerticalLine value
            IsVerticalLineValid (bool, optional): IsVerticalLineValid value
            Distance (int, optional): Distance value
            IsDistanceValid (bool, optional): IsDistanceValid value
        """
        self._top_line = None
        self._is_top_line_valid = None
        self._bottom_line = None
        self._is_bottom_line_valid = None
        self._left_line = None
        self._is_left_line_valid = None
        self._right_line = None
        self._is_right_line_valid = None
        self._horizontal_line = None
        self._is_horizontal_line_valid = None
        self._vertical_line = None
        self._is_vertical_line_valid = None
        self._distance = None
        self._is_distance_valid = None

        key_order = ('TopLine', 'IsTopLineValid', 'BottomLine', 'IsBottomLineValid', 'LeftLine', 'IsLeftLineValid', 'RightLine', 'IsRightLineValid', 'HorizontalLine', 'IsHorizontalLineValid', 'VerticalLine', 'IsVerticalLineValid', 'Distance', 'IsDistanceValid')
        arg_len = len(args)
        if arg_len == 1:
            if isinstance(args[0], TableBorder):
                oth = args[0]
                for key in key_order:
                    setattr(self, key, getattr(oth, key))
                return

        if  arg_len > len(key_order):
            raise ValueError("TableBorder.__init__() To many parameters")
        for i, arg in enumerate(args):
            setattr(self, key_order[i], arg)
        for k, v in kwargs.items():
            if k in key_order:
                setattr(self, k, v)


    @property
    def TopLine(self) -> 'BorderLine_a3f80af6':
        """
        determines the line style at the top edge.
        """
        return self._top_line
    
    @TopLine.setter
    def TopLine(self, value: 'BorderLine_a3f80af6') -> None:
        self._top_line = value

    @property
    def IsTopLineValid(self) -> bool:
        """
        specifies whether the value of TableBorder.TopLine is used.
        """
        return self._is_top_line_valid
    
    @IsTopLineValid.setter
    def IsTopLineValid(self, value: bool) -> None:
        self._is_top_line_valid = value

    @property
    def BottomLine(self) -> 'BorderLine_a3f80af6':
        """
        determines the line style at the bottom edge.
        """
        return self._bottom_line
    
    @BottomLine.setter
    def BottomLine(self, value: 'BorderLine_a3f80af6') -> None:
        self._bottom_line = value

    @property
    def IsBottomLineValid(self) -> bool:
        """
        specifies whether the value of TableBorder.BottomLine is used.
        """
        return self._is_bottom_line_valid
    
    @IsBottomLineValid.setter
    def IsBottomLineValid(self, value: bool) -> None:
        self._is_bottom_line_valid = value

    @property
    def LeftLine(self) -> 'BorderLine_a3f80af6':
        """
        determines the line style at the left edge.
        """
        return self._left_line
    
    @LeftLine.setter
    def LeftLine(self, value: 'BorderLine_a3f80af6') -> None:
        self._left_line = value

    @property
    def IsLeftLineValid(self) -> bool:
        """
        specifies whether the value of TableBorder.LeftLine is used.
        """
        return self._is_left_line_valid
    
    @IsLeftLineValid.setter
    def IsLeftLineValid(self, value: bool) -> None:
        self._is_left_line_valid = value

    @property
    def RightLine(self) -> 'BorderLine_a3f80af6':
        """
        determines the line style at the right edge.
        """
        return self._right_line
    
    @RightLine.setter
    def RightLine(self, value: 'BorderLine_a3f80af6') -> None:
        self._right_line = value

    @property
    def IsRightLineValid(self) -> bool:
        """
        specifies whether the value of TableBorder.RightLine is used.
        """
        return self._is_right_line_valid
    
    @IsRightLineValid.setter
    def IsRightLineValid(self, value: bool) -> None:
        self._is_right_line_valid = value

    @property
    def HorizontalLine(self) -> 'BorderLine_a3f80af6':
        """
        determines the line style of horizontal lines for the inner part of a cell range.
        """
        return self._horizontal_line
    
    @HorizontalLine.setter
    def HorizontalLine(self, value: 'BorderLine_a3f80af6') -> None:
        self._horizontal_line = value

    @property
    def IsHorizontalLineValid(self) -> bool:
        """
        specifies whether the value of TableBorder.HorizontalLine is used.
        """
        return self._is_horizontal_line_valid
    
    @IsHorizontalLineValid.setter
    def IsHorizontalLineValid(self, value: bool) -> None:
        self._is_horizontal_line_valid = value

    @property
    def VerticalLine(self) -> 'BorderLine_a3f80af6':
        """
        determines the line style of vertical lines for the inner part of a cell range.
        """
        return self._vertical_line
    
    @VerticalLine.setter
    def VerticalLine(self, value: 'BorderLine_a3f80af6') -> None:
        self._vertical_line = value

    @property
    def IsVerticalLineValid(self) -> bool:
        """
        specifies whether the value of TableBorder.VerticalLine is used.
        """
        return self._is_vertical_line_valid
    
    @IsVerticalLineValid.setter
    def IsVerticalLineValid(self, value: bool) -> None:
        self._is_vertical_line_valid = value

    @property
    def Distance(self) -> int:
        """
        contains the distance between the lines and other contents.
        """
        return self._distance
    
    @Distance.setter
    def Distance(self, value: int) -> None:
        self._distance = value

    @property
    def IsDistanceValid(self) -> bool:
        """
        specifies whether the value of TableBorder.Distance is used.
        """
        return self._is_distance_valid
    
    @IsDistanceValid.setter
    def IsDistanceValid(self, value: bool) -> None:
        self._is_distance_valid = value


__all__ = ['TableBorder']
