# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Const Class
# this is a auto generated file generated by Cheetah
# Libre Office Version: 7.2
# Namespace: com.sun.star.rendering
from enum import IntEnum


class PanoseArmStyle(object):
    """
    Const Class


    See Also:
        `API PanoseArmStyle <https://api.libreoffice.org/docs/idl/ref/namespacecom_1_1sun_1_1star_1_1rendering_1_1PanoseArmStyle.html>`_
    """
    ANYTHING = 0
    NO_FIT = 1
    STRAIGHT_HORIZONTAL = 2
    STRAIGHT_WEDGE = 3
    STRAIGHT_VERTICAL = 4
    STRAIGHT_SINGLE_SERIF = 5
    STRAIGHT_DOUBLE_SERIF = 6
    BENT_HORIZONTAL = 7
    BENT_WEDGE = 8
    BENT_VERTICAL = 9
    BENT_SINGLE_SERIF = 10
    BENT_DOUBLE_SERIF = 11


class PanoseArmStyleEnum(IntEnum):
    """
    Enum of Const Class PanoseArmStyle

    """
    ANYTHING = PanoseArmStyle.ANYTHING
    NO_FIT = PanoseArmStyle.NO_FIT
    STRAIGHT_HORIZONTAL = PanoseArmStyle.STRAIGHT_HORIZONTAL
    STRAIGHT_WEDGE = PanoseArmStyle.STRAIGHT_WEDGE
    STRAIGHT_VERTICAL = PanoseArmStyle.STRAIGHT_VERTICAL
    STRAIGHT_SINGLE_SERIF = PanoseArmStyle.STRAIGHT_SINGLE_SERIF
    STRAIGHT_DOUBLE_SERIF = PanoseArmStyle.STRAIGHT_DOUBLE_SERIF
    BENT_HORIZONTAL = PanoseArmStyle.BENT_HORIZONTAL
    BENT_WEDGE = PanoseArmStyle.BENT_WEDGE
    BENT_VERTICAL = PanoseArmStyle.BENT_VERTICAL
    BENT_SINGLE_SERIF = PanoseArmStyle.BENT_SINGLE_SERIF
    BENT_DOUBLE_SERIF = PanoseArmStyle.BENT_DOUBLE_SERIF

__all__ = ['PanoseArmStyle', 'PanoseArmStyleEnum']
