# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Exception Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.document
# Libre Office Version: 7.2
import typing
from ..beans.property_value import PropertyValue as PropertyValue_c9610c73
from ..uno.exception import Exception as Exception_85530a09
if typing.TYPE_CHECKING:
    from ..frame.x_model import XModel as XModel_7a6e095c

class FilterOptionsRequest(Exception_85530a09):
    """
    Is used for interaction handle to get filter options.
    
    **since**
    
        OOo 1.1.2

    See Also:
        `API FilterOptionsRequest <https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1document_1_1FilterOptionsRequest.html>`_
    """

    __ooo_ns__: str = 'com.sun.star.document'
    __ooo_full_ns__: str = 'com.sun.star.document.FilterOptionsRequest'
    __ooo_type_name__: str = 'exception'
    __pyunointerface__: str = 'com.sun.star.document.FilterOptionsRequest'
    __pyunostruct__: str = 'com.sun.star.document.FilterOptionsRequest'

    typeName: str = 'com.sun.star.document.FilterOptionsRequest'
    """Literal Constant ``com.sun.star.document.FilterOptionsRequest``"""

    rProperties: typing.TypeAlias = typing.Tuple[PropertyValue_c9610c73, ...]
    """
    The Media-descriptor of the document.
    """

    rModel: 'XModel_7a6e095c' = None
    """
        The model of the document that should be provided to filters that supports XExporter interface.
    """


