# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.xml.xpath
# Libre Office Version: 7.2


class Libxml2ExtensionHandle(object):
    """
    Struct Class


    See Also:
        `API Libxml2ExtensionHandle <https://api.libreoffice.org/docs/idl/ref/structcom_1_1sun_1_1star_1_1xml_1_1xpath_1_1Libxml2ExtensionHandle.html>`_
    """
    __ooo_ns__: str = 'com.sun.star.xml.xpath'
    __ooo_full_ns__: str = 'com.sun.star.xml.xpath.Libxml2ExtensionHandle'
    __ooo_type_name__: str = 'struct'
    typeName: str = 'com.sun.star.xml.xpath.Libxml2ExtensionHandle'
    """Literal Constant ``com.sun.star.xml.xpath.Libxml2ExtensionHandle``"""


    def __init__(self, *args, **kwargs):
        """
        Constructor

        Other Arguments:
            First positinal arg can be another ``Libxml2ExtensionHandle`` instance,
                if it is the only argument passed to contructor;
                Otherwise, postitional arguments are treated as ``Libxml2ExtensionHandle``
                values. Following the order of ``Keyword Arguments``.

        Keyword Arguments:
            functionLookupFunction (int, optional): functionLookupFunction value
            functionData (int, optional): functionData value
            variableLookupFunction (int, optional): variableLookupFunction value
            variableData (int, optional): variableData value
        """
        self._function_lookup_function = None
        self._function_data = None
        self._variable_lookup_function = None
        self._variable_data = None

        key_order = ('functionLookupFunction', 'functionData', 'variableLookupFunction', 'variableData')
        arg_len = len(args)
        if arg_len == 1:
            if isinstance(args[0], Libxml2ExtensionHandle):
                oth = args[0]
                for key in key_order:
                    setattr(self, key, getattr(oth, key))
                return

        if  arg_len > len(key_order):
            raise ValueError("Libxml2ExtensionHandle.__init__() To many parameters")
        for i, arg in enumerate(args):
            setattr(self, key_order[i], arg)
        for k, v in kwargs.items():
            if k in key_order:
                setattr(self, k, v)

    @property
    def functionLookupFunction(self) -> int:
        """
        """
        return self._function_lookup_function
    
    @functionLookupFunction.setter
    def functionLookupFunction(self, value: int) -> None:
        self._function_lookup_function = value

    @property
    def functionData(self) -> int:
        """
        """
        return self._function_data
    
    @functionData.setter
    def functionData(self, value: int) -> None:
        self._function_data = value

    @property
    def variableLookupFunction(self) -> int:
        """
        """
        return self._variable_lookup_function
    
    @variableLookupFunction.setter
    def variableLookupFunction(self, value: int) -> None:
        self._variable_lookup_function = value

    @property
    def variableData(self) -> int:
        """
        """
        return self._variable_data
    
    @variableData.setter
    def variableData(self, value: int) -> None:
        self._variable_data = value


__all__ = ['Libxml2ExtensionHandle']
