# coding: utf-8
#
# Copyright 2022 :Barry-Thomas-Paul: Moss
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http: // www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Struct Class
# this is a auto generated file generated by Cheetah
# Namespace: com.sun.star.i18n
# Libre Office Version: 7.2
from typing import TYPE_CHECKING
from ooo.oenv import UNO_ENVIRONMENT, UNO_RUNTIME, UNO_NONE
_DYNAMIC = False
if (not TYPE_CHECKING) and UNO_RUNTIME and UNO_ENVIRONMENT:
    _DYNAMIC = True

if not TYPE_CHECKING and _DYNAMIC:
    def _dynamic_struct():
        import uno
        from com.sun.star.i18n import LocaleDataItem as ULocaleDataItem
        # Dynamically create uno com.sun.star.i18n.LocaleDataItem using uno
        global LocaleDataItem

        def _set_fn_attr(struct):
            type_name = 'com.sun.star.i18n.LocaleDataItem'
            struct.__dict__['typeName'] = type_name
            struct.__dict__['__pyunointerface__'] = type_name
            struct.__dict__['__pyunostruct__'] = type_name

        def _set_attr(struct):
            struct.__dict__['__ooo_ns__'] = 'com.sun.star.i18n'
            struct.__dict__['__ooo_full_ns__'] = 'com.sun.star.i18n.LocaleDataItem'
            struct.__dict__['__ooo_type_name__'] = 'struct'

        def _struct_init(unoID = UNO_NONE, dateSeparator = UNO_NONE, thousandSeparator = UNO_NONE, decimalSeparator = UNO_NONE, timeSeparator = UNO_NONE, time100SecSeparator = UNO_NONE, listSeparator = UNO_NONE, quotationStart = UNO_NONE, quotationEnd = UNO_NONE, doubleQuotationStart = UNO_NONE, doubleQuotationEnd = UNO_NONE, timeAM = UNO_NONE, timePM = UNO_NONE, measurementSystem = UNO_NONE, LongDateDayOfWeekSeparator = UNO_NONE, LongDateDaySeparator = UNO_NONE, LongDateMonthSeparator = UNO_NONE, LongDateYearSeparator = UNO_NONE):
            ns = 'com.sun.star.i18n.LocaleDataItem'
            if isinstance(unoID, ULocaleDataItem):
                inst = uno.createUnoStruct(ns, unoID)
                _set_attr(inst)
                return inst
            struct = uno.createUnoStruct(ns)

            if not unoID is UNO_NONE:
                if getattr(struct, 'unoID') != unoID:
                    setattr(struct, 'unoID', unoID)
            if not dateSeparator is UNO_NONE:
                if getattr(struct, 'dateSeparator') != dateSeparator:
                    setattr(struct, 'dateSeparator', dateSeparator)
            if not thousandSeparator is UNO_NONE:
                if getattr(struct, 'thousandSeparator') != thousandSeparator:
                    setattr(struct, 'thousandSeparator', thousandSeparator)
            if not decimalSeparator is UNO_NONE:
                if getattr(struct, 'decimalSeparator') != decimalSeparator:
                    setattr(struct, 'decimalSeparator', decimalSeparator)
            if not timeSeparator is UNO_NONE:
                if getattr(struct, 'timeSeparator') != timeSeparator:
                    setattr(struct, 'timeSeparator', timeSeparator)
            if not time100SecSeparator is UNO_NONE:
                if getattr(struct, 'time100SecSeparator') != time100SecSeparator:
                    setattr(struct, 'time100SecSeparator', time100SecSeparator)
            if not listSeparator is UNO_NONE:
                if getattr(struct, 'listSeparator') != listSeparator:
                    setattr(struct, 'listSeparator', listSeparator)
            if not quotationStart is UNO_NONE:
                if getattr(struct, 'quotationStart') != quotationStart:
                    setattr(struct, 'quotationStart', quotationStart)
            if not quotationEnd is UNO_NONE:
                if getattr(struct, 'quotationEnd') != quotationEnd:
                    setattr(struct, 'quotationEnd', quotationEnd)
            if not doubleQuotationStart is UNO_NONE:
                if getattr(struct, 'doubleQuotationStart') != doubleQuotationStart:
                    setattr(struct, 'doubleQuotationStart', doubleQuotationStart)
            if not doubleQuotationEnd is UNO_NONE:
                if getattr(struct, 'doubleQuotationEnd') != doubleQuotationEnd:
                    setattr(struct, 'doubleQuotationEnd', doubleQuotationEnd)
            if not timeAM is UNO_NONE:
                if getattr(struct, 'timeAM') != timeAM:
                    setattr(struct, 'timeAM', timeAM)
            if not timePM is UNO_NONE:
                if getattr(struct, 'timePM') != timePM:
                    setattr(struct, 'timePM', timePM)
            if not measurementSystem is UNO_NONE:
                if getattr(struct, 'measurementSystem') != measurementSystem:
                    setattr(struct, 'measurementSystem', measurementSystem)
            if not LongDateDayOfWeekSeparator is UNO_NONE:
                if getattr(struct, 'LongDateDayOfWeekSeparator') != LongDateDayOfWeekSeparator:
                    setattr(struct, 'LongDateDayOfWeekSeparator', LongDateDayOfWeekSeparator)
            if not LongDateDaySeparator is UNO_NONE:
                if getattr(struct, 'LongDateDaySeparator') != LongDateDaySeparator:
                    setattr(struct, 'LongDateDaySeparator', LongDateDaySeparator)
            if not LongDateMonthSeparator is UNO_NONE:
                if getattr(struct, 'LongDateMonthSeparator') != LongDateMonthSeparator:
                    setattr(struct, 'LongDateMonthSeparator', LongDateMonthSeparator)
            if not LongDateYearSeparator is UNO_NONE:
                if getattr(struct, 'LongDateYearSeparator') != LongDateYearSeparator:
                    setattr(struct, 'LongDateYearSeparator', LongDateYearSeparator)
            _set_attr(struct)
            _set_fn_attr(struct)
            return struct
        _set_attr(_struct_init)
        LocaleDataItem = _struct_init

    _dynamic_struct()
else:
    from ...lo.i18n.locale_data_item import LocaleDataItem as LocaleDataItem

__all__ = ['LocaleDataItem']

